services:
  db:
    image: postgres:16-alpine
    container_name: csw430-postgres
    environment:
      POSTGRES_DB: csw430_project
      POSTGRES_USER: csw430
      POSTGRES_PASSWORD: csw430_local_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_demo:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/01-database.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csw430 -d csw430_project"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_demo:
